# Project information
site_name: Tedeapolis wet en regelgeving
site_url: https://wetboek.tedeapolis.nl/
site_description: 'wet en regelgeving van tedeapolis roleplay'
site_author: 'Tedeapolis'

# Copyright
copyright: Copyright &copy; 2019 - 2020 Tedeapolis

# Repository
repo_url: https://github.com/Tedeapolis/wet-en-regelgeving/
repo_name: Tedeapolis/wet-en-regelgeving
edit_uri: ""

# Google Analytics
google_analytics: ['UA-167800475-3', 'wetboek.tedeapolis.nl']

# Congiguration
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: preference
  favicon: img/logoTedeapolis.png
  logo: img/logoTedeapolis.png
  custom_dir: docs/overrides
  language: nl
plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: nl
      fallback_to_build_date: false
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
  - Belastingen: belastingen.md
  - Regelement voor de rechtspraak: rechtspraak.md
  - Kosten:
    - Advocatuur: kosten/advocatuur.md
    - Ambulence: kosten/ambulence.md
    - ANWB: kosten/anwb.md
    - Politie: kosten/politie.md
    - Vliegschool: kosten/vliegschool.md